trilioData/tvk-plugins

- docs/log-collector/README.md
- docs/preflight/README.md
Updated `os and arch` section of docs and enhanced readability of doc
> updated log-collector and preflight README.md

- .github/workflows/plugin-packages.yml
> TK-1581-fix: workflow invalid fix

- .github/workflows/plugin-packages.yml
- docs/RELEASE.md
CI cluster zone change in workflow yaml
> TK-1582: CI cluster zone change

- hack/check-git-diff-between-tags.sh
minor fix in fallback logic of creating release: need to set create_release var to true to create release
> TK-1582: minor fix in fallback logic of creating release

- .krew/tvk-log-collector.yaml
- .krew/tvk-preflight.yaml
- plugins/tvk-log-collector.yaml
- plugins/tvk-preflight.yaml
updated plugins yamls for release v1.0.0-rc1
> updated plugins yamls for release v1.0.0-rc1

- plugins/tvk-log-collector.yaml
- plugins/tvk-preflight.yaml
automated update of plugin manifests for v1.0.0-rc2 by script
> updated plugin manifests for v1.0.0-rc2

- docs/preflight/README.md
- tools/preflight/preflight.sh
closes: [bug](https://triliodata.atlassian.net/browse/TK-2726)
> TK-2726: SC and VSC drivers issue fixed

- cmd/log-collector/cmd/root.go
- docs/log-collector/README.md
- tools/log-collector/helper.go
- tools/log-collector/log_collector.go
Added Resources related to Cluster such as Node, Namespaces and Few Namespaced resources such as ResourceQuota and LimitRange, Role, ServiceAccount and OCP resources such as
1. ClusterServiceVersion  
2. CatalogSource
3. InstallPlan
4. OperatorCondition
5. Route
6. Subscription
> : seedling : TK-2662, TK-2778 : Restructured Code and Added Resources

- .github/workflows/plugin-packages.yml
added CI steps to access `secrets.NFS_SERVER_IP` from repo secret inside target-browser jobs
> 🌱TK-3220: secrets.NFS_SERVER_IP added in CI

- .github/workflows/plugin-packages.yml
- .krew/tvk-target-browser.yaml
- Makefile
- cmd/target-browser/cmd/get.go
- docs/CONTRIBUTION.md
- hack/generate-test-plugin-manifests.sh
- hack/generate-test-target-browser-plugin-manifest.sh
- hack/test-plugins-locally.sh
- hack/test-target-browser-plugin-locally.sh
- hack/update-log-collector-manifest.sh
- hack/update-plugin-manifests.sh
- hack/update-preflight-manifest.sh
- hack/update-target-browser-manifest.sh
-  target-browser krew plugin manifests changes to generate manifest to local testing
- script to generate final target-browser krew plugin manifest
> 🌱TK-3221: target-browser krew plugin manifests changes

- .github/workflows/plugin-packages.yml
- fixed kubeConfig expiry issue from test job
- added Test report publish step
> 🐛TK:3220: Fixed kubeConfig expiry issue

- .github/workflows/plugin-packages.yml
- .goreleaser.yml
- hack/check-git-diff-between-tags.sh
- hack/run-integration-tests.sh
- hack/update-goreleaser-yaml.sh
- uncommented target-browser release related code from CI as target-browser is ready for release.
> 🌱TK:3220: uncommented target-browser release related code from CI

- .krew/tvk-target-browser.yaml
- README.md
- cmd/target-browser/cmd/backup.go
- cmd/target-browser/cmd/backupPlan.go
- cmd/target-browser/cmd/get.go
- cmd/target-browser/cmd/metadata.go
- cmd/target-browser/cmd/root.go
- docs/log-collector/README.md
- docs/preflight/README.md
- docs/target-browser/README.md
- hack/test-preflight-plugin-locally.sh
Added documentation changes for target-browser plugin
> ✨TK-3223: added target-browser plugin doc

- cmd/target-browser/cmd/constant.go
- cmd/target-browser/cmd/get.go
- cmd/target-browser/cmd/root.go
- internal/constants.go
- tools/target-browser/auth.go
- tools/target-browser/backup.go
- tools/target-browser/client.go
- tools/target-browser/login.go
- tools/target-browser/utils.go
updated ssl connection for client
> TK-3223: updated ssl connection for client

- .github/workflows/plugin-packages.yml
- minor fixes in target-browser path filter
> TK-3220: updates to plugin-packages CI

- docs/preflight/README.md
- tools/preflight/preflight.sh
preflight doc & code update - removed redundant code and doc changes
> ✨TK-3223: preflight doc & code update - removed redundant parts

- .krew/tvk-target-browser.yaml
- cmd/target-browser/cmd/backup.go
- cmd/target-browser/cmd/backupPlan.go
- cmd/target-browser/cmd/metadata.go
- docs/target-browser/README.md
- tests/target-browser/target_browser_test.go
- tools/target-browser/backup.go
- tools/target-browser/backupplan.go
- tools/target-browser/field_selector.go
- tools/target-browser/metadata.go
> :seedling: TK-3421 Add support to get specfic backup and backupplan

- plugins/tvk-log-collector.yaml
- plugins/tvk-preflight.yaml
- plugins/tvk-target-browser.yaml
Added updated plugin yamls for v1.0.0-rc5 auto-generated by `make update-plugin-manifests`
> ✨TK-v1.0.0-rc5: updated plugin yamls for v1.0.0-rc5

- .github/workflows/plugin-packages.yml
ci-cluster zone changed to us-east1-b
> 🌱ci-cluster zone changed

- hack/run-integration-tests.sh
update resource limit and request in integration test
> :seeding: update resource limit and request in integration test

- .krew/tvk-target-browser.yaml
- cmd/target-browser/cmd/constant.go
- cmd/target-browser/cmd/resource-metadata.go
- docs/target-browser/README.md
- internal/constants.go
- tools/target-browser/backup.go
- tools/target-browser/metadata.go
- tools/target-browser/resource-metadata.go
Changes Done:
* Added resource-metadata CLI support for target-browser plugin
> :sparkles: TK-3425 Add CLI support to get Application YAMLs from backup

- .krew/tvk-target-browser.yaml
- cmd/target-browser/cmd/backup.go
- cmd/target-browser/cmd/constant.go
- cmd/target-browser/cmd/trilio-resources.go
- docs/target-browser/README.md
- internal/constants.go
- tools/target-browser/backup.go
- tools/target-browser/backupplan.go
- tools/target-browser/trilio-resources.go
- tools/target-browser/utils.go
Changes Done:
* Added code for handling `/trilio-resources` API
> :sparkles: TK-3424 Add support to get Trilio YAMLs

- cmd/target-browser/cmd/backup.go
- cmd/target-browser/cmd/backupPlan.go
- cmd/target-browser/cmd/trilio-resources.go
- cmd/target-browser/cmd/utils.go
- tools/target-browser/backup.go
- tools/target-browser/backupplan.go
- tools/target-browser/metadata.go
- tools/target-browser/resource-metadata.go
- tools/target-browser/trilio-resources.go
- tools/target-browser/utils.go
- code refactoring changes and improvements in target-browser CLI
> ✨TK-4004: code refactoring changes and improvements in target-browser CLI

- internal/constants.go
- internal/kube_helper.go
- internal/utils.go
- tests/target-browser/target_browser_suite_test.go
- tests/target-browser/target_browser_test.go
- tests/target-browser/test_helper.go
- tools/target-browser/auth.go
- tools/target-browser/utils.go
- Suppressed logs of k8s deprecated resources by client side configuration
- ingress version handling
- test suite fixed
> 🐛TK-4013: ingress version handling, Suppressed logs of k8s deprecated resources

- cmd/target-browser/cmd/backup.go
- cmd/target-browser/cmd/backupPlan.go
- cmd/target-browser/cmd/constant.go
- cmd/target-browser/cmd/get.go
- tests/target-browser/target_browser_test.go
- tools/target-browser/backup.go
- tools/target-browser/backupplan.go
- tools/target-browser/commons.go
- tools/target-browser/field_selector.go
Add tvk instanceID in backup subcommand and test case
> :sparkles:  TK-3423 Add tvk instanceID in sub command backup and testcase

- .github/workflows/plugin-packages.yml
- .golangci.yaml
- tests/preflight/preflight_test.sh
- tools/log-collector/helper.go
- tools/preflight/preflight.sh
- preflight script updated for min k8s v1.18
- golangci-lint-version updated to 1.42
> ✨TK-4052: preflight script updated for min k8s v1.18

- plugins/tvk-log-collector.yaml
- plugins/tvk-preflight.yaml
- plugins/tvk-target-browser.yaml
- updated plugin manifests for release v1.0.0-rc6
> ✨updated plugin manifests for v1.0.0-rc6

- tests/target-browser/createBackups.sh
- tools/preflight/preflight.sh
- skipping 'VOLUME_SNAPSHOT' check if 'STORAGE_SNAPSHOT_CLASS' check failed as these are dependent checks
> ✨TK-4134: skipping 'VOLUME_SNAPSHOT' check if 'STORAGE_SNAPSHOT_CLASS' check failed

- .krew/tvk-target-browser.yaml
- plugins/tvk-log-collector.yaml
- plugins/tvk-preflight.yaml
- plugins/tvk-target-browser.yaml
- updated manifests for v1.0.0 release
> ✨TK-v1.0.0: updated krew manifests for v1.0.0 release

- cmd/target-browser/cmd/backup.go
- cmd/target-browser/cmd/backupPlan.go
- cmd/target-browser/cmd/metadata.go
- cmd/target-browser/cmd/resource-metadata.go
- cmd/target-browser/cmd/trilio-resources.go
- cmd/target-browser/cmd/utils.go
- hack/run-integration-tests.sh
- tests/target-browser/target_browser_suite_test.go
- tests/target-browser/target_browser_test.go
- tests/target-browser/test-data/backup-metadata-all.json
- tests/target-browser/test_files/backup-all.json
- tests/target-browser/test_files/backupplan-all.json
- tests/target-browser/test_helper.go
>  :seedling: TK-3964 Update TB CLI testcase and refactor

- .github/workflows/plugin-packages.yml
- .krew/tvk-cleanup.yaml
- Makefile
- docs/cleanup/README.md
- hack/build-cleanup-artifacts.sh
- hack/generate-test-cleanup-plugin-manifest.sh
- hack/test-cleanup-plugin-locally.sh
- hack/update-cleanup-manifest.sh
- hack/update-goreleaser-yaml.sh
- hack/update-plugin-manifests.sh
- tests/cleanup/cleanup_test.sh
- tools/cleanup/cleanup.sh
Rebase and adding krew plugin files for tvk-cleanup
> :warning: Rebase and adding krew plugin files for tvk-cleanup

- .github/workflows/plugin-packages.yml
- Makefile
- hack/check-git-diff-between-tags.sh
- hack/update-goreleaser-yaml.sh
- release process related script changes
> 🌱TK:4315: release process related script changes

- plugins/tvk-cleanup.yaml
- plugins/tvk-log-collector.yaml
- plugins/tvk-oneclick.yaml
- plugins/tvk-preflight.yaml
- plugins/tvk-target-browser.yaml
updated krew yamls for v1.1.0-rc1
> TK-4315: updated krew yamls for v1.1.0-rc1

- hack/run-shell-lint.sh
- tests/target-browser/target_browser_test.go
- tests/tvk-oneclick/create_virtual_cluster.sh
- tests/tvk-oneclick/tvk_oneclick_test.sh
- tools/cleanup/cleanup.sh
- tools/preflight/preflight.sh
- tools/tvk-oneclick/tvk-oneclick.sh
> :sparkles: TK-4290: Added support for log files and resource limit

- cmd/target-browser/cmd/backup.go
- tests/target-browser/target_browser_test.go
- tests/target-browser/test_helper.go
> :seedling: TK-4098 Update and Add missing testcase for flag creation and expiry date 

- tools/preflight/preflight.sh
- preflight script syntax issues fixed for bash (<v4.x.x) which is pre-installed version in case of Mac.
>  🐛TK-4564: preflight syntax issues fixed for bash (<v4.x.x)

- docs/CONTRIBUTION.md
- plugins/tvk-oneclick.yaml
- plugins/tvk-preflight.yaml
- plugins/tvk-target-browser.yaml
> TK-v1.1.0-rc3: updated krew manifests for v1.1.0-rc3

- README.md
- docs/preflight/README.md
README doc updated with plugin installation with proxy
> 📖TK-4619: README doc updated with plugin installation with proxy

- hack/run-integration-tests.sh
- internal/constants.go
- tests/target-browser/target_browser_test.go
- tools/target-browser/auth.go
- tools/target-browser/backup.go
- tools/target-browser/login.go
- tools/target-browser/utils.go
>  :seedling: TK-4342 Add nodeport support

- docs/cleanup/README.md
- tools/cleanup/cleanup.sh
Minor changes for tvk-cleanup krew plugin for 2.6.x releases
> :warning: tvk-cleanup krew plugin changes for 2.6.x releases

- .krew/tvk-target-browser.yaml
- cmd/target-browser/cmd/backup.go
- cmd/target-browser/cmd/backupPlan.go
- cmd/target-browser/cmd/get.go
- cmd/target-browser/cmd/metadata.go
- cmd/target-browser/cmd/resource-metadata.go
- cmd/target-browser/cmd/trilio-resources.go
- docs/target-browser/README.md
- tests/target-browser/target_browser_test.go
> :book: TK-4702 Update target browser docs

- README.md
- docs/cleanup/README.md
- docs/log-collector/README.md
- docs/preflight/README.md
- docs/target-browser/README.md
- docs/tvk-oneclick/README.md
- tools/preflight/preflight.sh
documentation for plugin installation without krew
> 📖TK-4699: documentation for plugin installation without krew

- cmd/target-browser/cmd/get.go
- tools/target-browser/commons.go
> :seedlings: TK-4118: Added CLI Param for Listing Filtering

- README.md
- docs/cleanup/README.md
- docs/preflight/README.md
- if kubectl is not installed on host machine, doc has steps to follow.
> 📖TK-4699: updated doc with steps - if kubectl is not present

- README.md
- docs/cleanup/README.md
- docs/preflight/README.md
- updated preflight and cleanup plugins docs with steps if kubectl is not installed and oc is installed
> 📖TK-4699: updated preflight and cleanup plugins docs if kubectl is not installed

- hack/run-integration-tests.sh
Appended random char to namespace’s name so that on re-running jobs, it’ll not conflict with other runs of the same pipeline
>  🐛Tk-5253: CI script fix for NS creation/deletion

- docs/target-browser/README.md
- hack/run-integration-tests.sh
- internal/constants.go
- tests/target-browser/target_browser_suite_test.go
- tests/target-browser/target_browser_test.go
- tools/target-browser/auth.go
- tools/target-browser/login.go
- tools/target-browser/utils.go
- tools/tvk-oneclick/tvk-oneclick.sh
Updated ingress service name
updated tvkhost
fixed target browser test cases
> :seedling: TK-5202 update ingress service name

- .krew/tvk-target-browser.yaml
- cmd/target-browser/cmd/backup.go
- cmd/target-browser/cmd/backupPlan.go
- cmd/target-browser/cmd/constant.go
- cmd/target-browser/cmd/get.go
- docs/target-browser/README.md
- plugins/tvk-target-browser.yaml
- tests/target-browser/createBackups.sh
- tests/target-browser/target_browser_suite_test.go
- tests/target-browser/target_browser_test.go
- tests/target-browser/test_files/backup.json
- tests/target-browser/test_files/backupplan.json
- tests/target-browser/test_files/tvk-meta.json
- tests/target-browser/test_helper.go
- tools/target-browser/backup.go
- tools/target-browser/backupplan.go
- tools/target-browser/commons.go
- tools/target-browser/field_selector.go
> :seedling: TK-5268 Add flag in TB for tvkInstanceName

- tools/preflight/helper.go
Added sync command before the sleep command on source pod for volume snapshot to synchronize data of write operation in the source pod volume.
> :seedling: TK-5068 Handle Timing Issue in Pre-flight

- cmd/log-collector/cmd/constants.go
- cmd/log-collector/cmd/helper.go
- cmd/log-collector/cmd/root.go
- docs/log-collector/README.md
- docs/log-collector/sample_input.yaml
- tools/log-collector/helper.go
- tools/log-collector/log_collector.go
> :sparklings: TK-4757: Log Collector Enhancements

- .github/workflows/plugin-packages.yml
- docker-images/preflight/Dockerfile
> 🌱 TK-5288: CI changes to build and push preflight image

- tools/log-collector/helper.go
- tools/log-collector/log_collector.go
> :seedlings: LC Fix for Non labeled CSV Resources

- docs/preflight/README.md
> 📖 TK-5630: update README.md for preflight checks and flags changes

- tools/preflight/cleanup.go
- tools/preflight/helper.go
- tools/preflight/preflight.go
While deleting resources, sometimes an error occurs - resource not found.
Fix for that is provided in this patch
> :bug: preflight cleanup error bug fix

- .github/workflows/plugin-manifests.yml
- plugins/tvk-log-collector.yaml
- plugins/tvk-oneclick.yaml
- plugins/tvk-preflight.yaml
- plugins/tvk-target-browser.yaml
> ✨TK-v2.0.0-rc.1: updated plugins for v2.0.0-rc.1

- hack/check-git-diff-between-tags.sh
- plugins/tvk-preflight.yaml
> ✨TK-v1.2.0-rc.1: updated plugin yaml for preflight release

- tools/log-collector/log_collector.go
> 🌱 Fix Minor Issue on OCP

- docs/preflight/README.md
- tests/preflight/preflight_suite_test.go
- tools/preflight/helper.go
- tools/preflight/preflight.go
- tools/preflight/preflight_test.go
> 🐛 TK-5678: Bug fix for volumesnapshotclass created with fixed name

- tools/log-collector/helper.go
- tools/log-collector/log_collector.go
> :sparklings: TK-5765: Added OLM Owner Resources on Label

- .github/workflows/plugin-packages.yml
- hack/run-unit-tests.sh
> 🌱 TK-5755: Changes for preflight docker build CI to push latest tag only for versioned release

- .github/workflows/plugin-packages.yml
> 🌱 Updated Workflow to Upload Artifacts

- .github/workflows/plugin-packages.yml
- hack/run-integration-tests.sh
> ✨ change gke zone to region

- .github/workflows/plugin-packages.yml
- hack/run-integration-tests.sh
> Tk 5916: get zone of specific node

- cmd/log-collector/cmd/cmd_test.go
- cmd/log-collector/cmd/helper.go
- cmd/log-collector/cmd/root.go
- docs/log-collector/README.md
- internal/kube_helper.go
- tools/log-collector/log_collector.go
> :sparklings: TK-5896: Updated Kubeconfig Path Logic

- tools/preflight/helper.go
- tools/preflight/preflight.go
- tools/preflight/preflight_test.go
> :sparkles: TK-5990 Add warning and additional wait time when volume snapshot does not reach ready state

- tools/preflight/helper.go
- tools/preflight/preflight.go
Please review PR @prasad-trilio @pallav-trilio and let me know changes if required.
> ✨ [TK-6045] Add logs to print the yaml/json of preflight resources when failed to create

- tools/preflight/helper.go
- tools/preflight/preflight.go
> 🐛fix: Fix the logic to get the default volumeSnapshotClass

- tests/preflight/helpers_test.go
- tools/preflight/preflight.go
> :seedling:  TK-8518 Fix preflight integration tests

- cmd/log-collector/cmd/root.go
- cmd/preflight/cmd/root.go
- internal/kube_helper.go
> :bug: TK-7101 priodic-operator-e2e job failing fix

- docs/log-collector/README.md
- docs/preflight/README.md
log-collector output after script run on mac os: 
```
+-zsh:95> mktemp -d
+-zsh:95> cd /var/folders/yk/rqyrdd4j0qv0t45bx13vy1gw0000gp/T/tmp.Wqg9IZzwtK
+-zsh:96> OS=+-zsh:96> uname
+-zsh:96> OS=+-zsh:96> tr '[:upper:]' '[:lower:]'
+-zsh:96> OS=darwin 
+-zsh:97> ARCH=+-zsh:97> uname -m
+-zsh:97> ARCH=+-zsh:97> sed -e s/x86_64/amd64/ -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/'
+-zsh:97> ARCH=arm64 
+-zsh:98> [[ -z '' ]]
+-zsh:98> version=+-zsh:98> curl -s https://api.github.com/repos/trilioData/tvk-plugins/releases/latest
+-zsh:98> version=+-zsh:98> grep tag_name
+-zsh:98> version=+-zsh:98> awk '{print $2}'
+-zsh:98> version=+-zsh:98> tr -d '",'
+-zsh:98> version=v1.3.0 
+-zsh:99> echo 'Installing version=v1.3.0'
Installing version=v1.3.0
+-zsh:100> …
```
> :book: TK-9014 Bash install commands for preflight and log collector

- .goreleaser.yml
> :sparkles: add support of ppc64le

- .github/workflows/plugin-packages.yml
- Makefile
- hack/generate-test-log-collector-plugin-manifest.sh
- hack/generate-test-preflight-plugin-manifest.sh
> :bug: TK-9344 failures in build-test jobs for preflight and log-collector

- .github/workflows/plugin-packages.yml
- docker-images/preflight/Dockerfile
> :bug: TK-9553 preflight fix

- .github/workflows/plugin-packages.yml
- plugins/tvk-log-collector.yaml
- plugins/tvk-preflight.yaml
Release v1.3.2 for log-collector and preflight plugin
> 🌱 Release/v1.3.2
